MOUNTING_POINT="$HOME/Desktop/smb"
# FORMAT:
# NAME|PARENT_DIR|SOURCE_DIR
    # NAME: the Backup task name (up to you)
    # PARENT_DIR: where is the backup (including TARGET_DIR and changed Folder)
    # SOURCE_DIR: the folder of your backup source
"scripts"|"$HOME/Desktop/smb/备份/ShellBackup"|"$HOME/scripts/"
.config|$HOME/Desktop/smb/备份/ShellBackup|$HOME/.config/
